// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtb_YwERYRQZrEA-sBSAG79MiwwKgZ_y0',
    appId: '1:751142741745:web:a486be86b68c8142c02b50',
    messagingSenderId: '751142741745',
    projectId: 'fir-master-class-f7e61',
    authDomain: 'fir-master-class-f7e61.firebaseapp.com',
    storageBucket: 'fir-master-class-f7e61.appspot.com',
    measurementId: 'G-1B5SQGW2MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgf43xRWqFbqT8M7kSEDcd21xXj9TPJTE',
    appId: '1:751142741745:android:1973c8afbea70433c02b50',
    messagingSenderId: '751142741745',
    projectId: 'fir-master-class-f7e61',
    storageBucket: 'fir-master-class-f7e61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YEBZarPw1T41sk5qXoi-CES0OGysk3s',
    appId: '1:751142741745:ios:71eae2550d8c5fbfc02b50',
    messagingSenderId: '751142741745',
    projectId: 'fir-master-class-f7e61',
    storageBucket: 'fir-master-class-f7e61.appspot.com',
    iosClientId: '751142741745-o29fj7lfdugjp7flka88sck8prv8svhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMasterClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9YEBZarPw1T41sk5qXoi-CES0OGysk3s',
    appId: '1:751142741745:ios:71eae2550d8c5fbfc02b50',
    messagingSenderId: '751142741745',
    projectId: 'fir-master-class-f7e61',
    storageBucket: 'fir-master-class-f7e61.appspot.com',
    iosClientId: '751142741745-o29fj7lfdugjp7flka88sck8prv8svhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMasterClass',
  );
}
